import sqlite3

con = sqlite3.connect("clones.db")
con.execute("create table clone_data (uid INTEGER PRIMARY KEY AUTOINCREMENT, Clone1 TEXT NOT NULL,Start1 INTEGER NOT NULL,End1 INTEGER NOT NULL, Clone2 TEXT NOT NULL,Start2 INTEGER NOT NULL,End2 INTEGER NOT NULL, BCB_RATING INTEGER NOT NULL, P1 INTEGER NOT NULL, P2 INTEGER NOT NULL)")
#con.execute('create table clone_data START1 INTEGER NOT NULL, ADD COLUMN END1 INTEGER NOT NULL, ADD COLUMN START2 INTEGER NOT NULL, ADD COLUMN END2 INTEGER NOT NULL)')
con.close()

